// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAko5Q0QtlHIoM6VL_GBlLmI6oe7W5VOY8',
    appId: '1:453370936021:web:3f67c4456ff1373bae405c',
    messagingSenderId: '453370936021',
    projectId: 'ironcore-gear',
    authDomain: 'ironcore-gear.firebaseapp.com',
    storageBucket: 'ironcore-gear.firebasestorage.app',
    measurementId: 'G-X8183DJWEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXgQq_tsHWrRYgaSx-QWKlM8-UMrGWSuE',
    appId: '1:453370936021:android:d06a7004f253f656ae405c',
    messagingSenderId: '453370936021',
    projectId: 'ironcore-gear',
    storageBucket: 'ironcore-gear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAO9RuhfgBWt9WyqEaxDZjTxgGEKUmRoE',
    appId: '1:453370936021:ios:9e612920a7276dd2ae405c',
    messagingSenderId: '453370936021',
    projectId: 'ironcore-gear',
    storageBucket: 'ironcore-gear.firebasestorage.app',
    iosClientId: '453370936021-3qj7dt3b36ldqddo0v4n78v5scm6r2ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartSecurityResidence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAO9RuhfgBWt9WyqEaxDZjTxgGEKUmRoE',
    appId: '1:453370936021:ios:9e612920a7276dd2ae405c',
    messagingSenderId: '453370936021',
    projectId: 'ironcore-gear',
    storageBucket: 'ironcore-gear.firebasestorage.app',
    iosClientId: '453370936021-3qj7dt3b36ldqddo0v4n78v5scm6r2ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartSecurityResidence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAko5Q0QtlHIoM6VL_GBlLmI6oe7W5VOY8',
    appId: '1:453370936021:web:73aba9e86220f9f1ae405c',
    messagingSenderId: '453370936021',
    projectId: 'ironcore-gear',
    authDomain: 'ironcore-gear.firebaseapp.com',
    storageBucket: 'ironcore-gear.firebasestorage.app',
    measurementId: 'G-MBWLZ03BZT',
  );
}
